FROM python:3.6

# Сатвим питон руками
#RUN apt update -y
#RUN apt install software-properties-common -y
#RUN add-apt-repository ppa:deadsnakes/ppa
#RUN apt update -y
#RUN apt install python3.6 -y

# Копируем файлы
ADD ./index.py ./index.py

# Команда по умолчанию, можно переопределить
# CMD ["python3", "index.py"]
